# Generated by Django 5.1.2 on 2024-11-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_knowledgebase_chatbot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='knowledgebase',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='knowledgebase',
            field=models.ManyToManyField(blank=True, to='api.knowledgebase'),
        ),
    ]
