# Generated by Django 5.1.2 on 2024-11-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_chatbot_knowledgebase_chatbot_knowledgebase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='update_user',
        ),
    ]
