# Generated by Django 5.1.2 on 2024-11-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_faq_create_date_remove_faq_create_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot',
            old_name='first_message_tk',
            new_name='first_message_tr',
        ),
        migrations.RenameField(
            model_name='chatbot',
            old_name='welcome_additional_text_tk',
            new_name='welcome_additional_text_tr',
        ),
        migrations.RenameField(
            model_name='chatbot',
            old_name='welcome_text_tk',
            new_name='welcome_text_tr',
        ),
        migrations.RenameField(
            model_name='chatbot',
            old_name='welcome_title_tk',
            new_name='welcome_title_tr',
        ),
    ]
