# Generated by Django 5.1.3 on 2024-11-29 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_faqcategory_alter_faq_options_faq_answer_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqcategory',
            name='knowledgebase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.knowledgebase'),
        ),
    ]
