# Generated by Django 5.1.3 on 2024-12-09 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_faqcategory_knowledgebase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbot',
            options={'verbose_name': 'Chatbot', 'verbose_name_plural': 'Chatbots'},
        ),
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'verbose_name': 'Knowledgebase', 'verbose_name_plural': 'Knowledgebases'},
        ),
        migrations.AddField(
            model_name='chatbot',
            name='tech_contact_email',
            field=models.EmailField(default='', max_length=254, verbose_name='technical contact email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatbot',
            name='tech_contact_name',
            field=models.CharField(default='', max_length=255, verbose_name='technical contact name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='assistant_name',
            field=models.CharField(max_length=255, verbose_name='assistant name'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='chatbot_images/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='contact email'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='contact_name',
            field=models.CharField(max_length=255, verbose_name='contact name'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='first_message',
            field=models.CharField(max_length=255, verbose_name='first message'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='first_message_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='first message'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='first_message_de',
            field=models.CharField(max_length=255, null=True, verbose_name='first message'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='first_message_en',
            field=models.CharField(max_length=255, null=True, verbose_name='first message'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='first_message_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='first message'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='first_message_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='first message'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='header_title',
            field=models.CharField(max_length=255, verbose_name='header title'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='knowledgebase',
            field=models.ManyToManyField(blank=True, to='api.knowledgebase', verbose_name='knowledgebase'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='chatbot_images/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='primary_color',
            field=models.CharField(max_length=7, verbose_name='primary color'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='text_color',
            field=models.CharField(max_length=7, verbose_name='text color'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='welcome_additional_text',
            field=models.TextField(verbose_name='welcome additional text'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='welcome_additional_text_ar',
            field=models.TextField(null=True, verbose_name='welcome additional text'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='welcome_additional_text_de',
            field=models.TextField(null=True, verbose_name='welcome additional text'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='welcome_additional_text_en',
            field=models.TextField(null=True, verbose_name='welcome additional text'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='welcome_additional_text_ru',
            field=models.TextField(null=True, verbose_name='welcome additional text'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='welcome_additional_text_tr',
            field=models.TextField(null=True, verbose_name='welcome additional text'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='welcome_text',
            field=models.TextField(verbose_name='welcome text'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='welcome_text_ar',
            field=models.TextField(null=True, verbose_name='welcome text'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='welcome_text_de',
            field=models.TextField(null=True, verbose_name='welcome text'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='welcome_text_en',
            field=models.TextField(null=True, verbose_name='welcome text'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='welcome_text_ru',
            field=models.TextField(null=True, verbose_name='welcome text'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='welcome_text_tr',
            field=models.TextField(null=True, verbose_name='welcome text'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='welcome_title',
            field=models.TextField(verbose_name='welcome title'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='welcome_title_ar',
            field=models.TextField(null=True, verbose_name='welcome title'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='welcome_title_de',
            field=models.TextField(null=True, verbose_name='welcome title'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='welcome_title_en',
            field=models.TextField(null=True, verbose_name='welcome title'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='welcome_title_ru',
            field=models.TextField(null=True, verbose_name='welcome title'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='welcome_title_tr',
            field=models.TextField(null=True, verbose_name='welcome title'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(default='', verbose_name='answer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ar',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_de',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_tr',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='api.faqcategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(default='', verbose_name='question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ar',
            field=models.TextField(null=True, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_de',
            field=models.TextField(null=True, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_en',
            field=models.TextField(null=True, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ru',
            field=models.TextField(null=True, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_tr',
            field=models.TextField(null=True, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='knowledgebase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.knowledgebase', verbose_name='knowledgebase'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
