# Generated by Django 5.1.3 on 2024-12-09 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_chatbot_options_alter_knowledgebase_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqcategory',
            name='knowledgebase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.knowledgebase', verbose_name='knowledgebase'),
        ),
    ]
