# Generated by Django 5.1.3 on 2024-12-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_faqcategory_knowledgebase'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='main_prompt_extras',
            field=models.TextField(default='', verbose_name='prompt extras for main prompt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatbot',
            name='query_optimizer_extras',
            field=models.TextField(default='', verbose_name='prompt extras for query-optimizer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatbot',
            name='related_questions_extras',
            field=models.TextField(default='', verbose_name='prompt extras for related questions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatbot',
            name='no_sources_extras',
            field=models.TextField(default='', verbose_name='prompt extras for for no sources answer'),
            preserve_default=False,
        ),
    ]
