# Generated by Django 5.1.3 on 2025-01-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_faq_answer_ar_remove_faq_answer_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='rag_type',
            field=models.CharField(choices=[('simple', 'SIMPLE'), ('VIPR', 'VIPR')], default='simple', max_length=10),
        ),
    ]
