# Generated by Django 5.1.3 on 2025-02-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_chatbot_rag_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='chatbot_type',
            field=models.CharField(choices=[('default', 'Default'), ('glass', 'glass')], default='general', max_length=20, verbose_name='Chatbot Variant'),
        ),
    ]
