# Generated by Django 5.1.3 on 2025-02-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_chatbot_chatbot_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot',
            old_name='chatbot_type',
            new_name='chatbot_variant',
        ),
    ]
