# Generated by Django 5.1.3 on 2025-02-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_chatbot_type_chatbot_chatbot_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='chatbot_variant',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='chatbot_style',
            field=models.CharField(choices=[('default', 'Default'), ('glass', 'Glass')], default='general', max_length=20, verbose_name='Chatbot Style'),
        ),
    ]
