# Generated by Django 5.1.3 on 2025-04-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_chatbot_variant_to_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='chatbot_style',
            field=models.CharField(choices=[('default', 'Default'), ('glass', 'Glass (same as default)'), ('dosb', 'DOSB')], default='default', max_length=20, verbose_name='Chatbot Style'),
        ),
    ]
