# Generated by Django 5.1.2 on 2024-11-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('deep', models.BooleanField(default=False)),
                ('file_deep_changed', models.BooleanField(default=False)),
                ('deletion_timeout', models.DateTimeField(null=True)),
                ('last_crawl_start', models.DateTimeField(null=True)),
                ('last_crawl_end', models.DateTimeField(null=True)),
                ('number_of_resources_processed', models.IntegerField(null=True)),
                ('content_selector', models.CharField(max_length=255, null=True)),
                ('excluded_selectors', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crawl_links',
            },
        ),
    ]
