# Generated by Django 5.1.2 on 2024-11-14 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_faq_create_date_remove_faq_create_user_and_more'),
        ('crawler', '0002_alter_crawllink_content_selector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawllink',
            name='knowledgebase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.knowledgebase'),
        ),
    ]
