# Generated by Django 5.1.3 on 2024-12-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_crawllink_knowledgebase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crawllink',
            options={'verbose_name': 'Crawl Link', 'verbose_name_plural': 'Crawl Links'},
        ),
    ]
