# Generated by Django 5.1.3 on 2024-11-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_crawllink_knowledgebase'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawllink',
            name='crawling_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('stopping', 'Stopping')], default='pending', max_length=10),
        ),
    ]
