# Generated by Django 5.1.3 on 2024-12-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_alter_crawllink_crawling_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawllink',
            name='crawling_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('stopping', 'Stopping')], default='pending', max_length=10),
        ),
    ]
