# Generated by Django 5.1.3 on 2024-12-10 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_alter_crawllink_options'),
        ('crawler', '0006_alter_crawllink_crawling_status'),
    ]

    operations = [
    ]
