# Generated by Django 5.1.3 on 2024-12-10 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_faqcategory_knowledgebase'),
        ('crawler', '0007_merge_20241210_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawllink',
            name='content_selector',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Content Selector'),
        ),
        migrations.AlterField(
            model_name='crawllink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='crawllink',
            name='deep',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Follow all links'),
        ),
        migrations.AlterField(
            model_name='crawllink',
            name='deletion_timeout',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delete missing resources after days'),
        ),
        migrations.AlterField(
            model_name='crawllink',
            name='excluded_selectors',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Excluded Selectors'),
        ),
        migrations.AlterField(
            model_name='crawllink',
            name='file_deep_changed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Disable file change detection optimization'),
        ),
        migrations.AlterField(
            model_name='crawllink',
            name='knowledgebase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.knowledgebase', verbose_name='Knowledgebase'),
        ),
        migrations.AlterField(
            model_name='crawllink',
            name='last_crawl_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Crawl End'),
        ),
        migrations.AlterField(
            model_name='crawllink',
            name='last_crawl_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Crawl Start'),
        ),
        migrations.AlterField(
            model_name='crawllink',
            name='number_of_resources_processed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Resources Processed'),
        ),
        migrations.AlterField(
            model_name='crawllink',
            name='url',
            field=models.URLField(unique=True, verbose_name='Website-URL'),
        ),
    ]
