# Generated by Django 5.1.3 on 2024-12-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0008_alter_crawllink_content_selector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawllink',
            name='crawling_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('stopping', 'Stopping')], default='pending', max_length=10, verbose_name='Crawling Status'),
        ),
    ]
