# Generated by Django 5.1.3 on 2024-12-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_alter_crawllink_crawling_status'),
        ('crawler', '0009_crawl_link_configuration'),
    ]

    operations = [
    ]
