# Generated by Django 5.1.3 on 2024-12-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0010_merge_20241211_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawllink',
            name='content_selector',
            field=models.CharField(blank=True, help_text="A selector in which webpage content is found; For Example Typo3 '#main'-selector", max_length=255, null=True, verbose_name='Content Selector'),
        ),
        migrations.AlterField(
            model_name='crawllink',
            name='crawl_interval',
            field=models.IntegerField(default=0, help_text="Time (in days) after which an already crawled resource is crawled again.\n The value '0' disables recrawling. The crawling interval  needs to be less than the delete intervall", verbose_name='Crawling interval'),
        ),
        migrations.AlterField(
            model_name='crawllink',
            name='deletion_timeout',
            field=models.IntegerField(default=0, help_text="Time (in days) after which an already crawled resource is deleted.\n The value '0' disables resource deletion", verbose_name='Delete missing resources after days'),
        ),
        migrations.AlterField(
            model_name='crawllink',
            name='excluded_selectors',
            field=models.CharField(blank=True, help_text='A comma-separated list of selectors, to be removed before content processing', max_length=255, null=True, verbose_name='Excluded Selectors'),
        ),
        migrations.AlterField(
            model_name='crawllink',
            name='file_deep_changed',
            field=models.BooleanField(default=False, help_text='If the resource is a pdf, check the whole pdf instead of the first 1024 bytes', null=True, verbose_name='Disable file change detection optimization'),
        ),
        migrations.AlterField(
            model_name='crawllink',
            name='last_crawl_end',
            field=models.DateTimeField(blank=True, help_text='The date and time the last crawl finished', null=True, verbose_name='Last Crawl End'),
        ),
        migrations.AlterField(
            model_name='crawllink',
            name='last_crawl_start',
            field=models.DateTimeField(blank=True, help_text='The date and time the link was last cralwed', null=True, verbose_name='Last Crawl Start'),
        ),
        migrations.AlterField(
            model_name='crawllink',
            name='number_of_resources_processed',
            field=models.IntegerField(blank=True, help_text='The number of resources found in the crawl', null=True, verbose_name='Number of Resources Processed'),
        ),
        migrations.AlterField(
            model_name='crawllink',
            name='requeue_duplicates',
            field=models.BooleanField(default=False, help_text='Requeue already existing resources for RAG Processing, else only new content is processed', null=True, verbose_name='Requeue found duplicates'),
        ),
    ]
