# Generated by Django 5.1.3 on 2024-12-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0011_alter_crawllink_content_selector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawllink',
            name='file_deep_changed',
        ),
        migrations.RemoveField(
            model_name='crawllink',
            name='requeue_duplicates',
        ),
        migrations.AddField(
            model_name='crawllink',
            name='deep_crawl',
            field=models.BooleanField(default=False, help_text='Crawl the entire page or only the provided link', verbose_name='Deep Crawl'),
        ),
    ]
