# Generated by Django 5.1.3 on 2025-04-02 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_create_user_profiles'),
        ('crawler', '0013_alter_crawllink_deep_crawl'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawllink',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crawl_links', to='api.tenant'),
        ),
    ]
