# Generated by Django 5.1.3 on 2025-04-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0014_crawllink_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawllink',
            name='custom_cookies',
            field=models.TextField(help_text="Custom Cookies to crawl a page. seperated by ','", null=True, verbose_name='Custom Cookies'),
        ),
    ]
