# Generated by Django 5.1.3 on 2025-04-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0016_crawllink_blacklist_patterns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawllink',
            name='blacklist_patterns',
            field=models.JSONField(blank=True, default=list, help_text="List of URL patterns to exclude from crawling (e.g. ['/blog/*', '/private/*'])", null=True, verbose_name='Blacklisted URL Patterns'),
        ),
        migrations.AlterField(
            model_name='crawllink',
            name='custom_cookies',
            field=models.JSONField(default=list, help_text='Pre-set cookies, each a dict like {"name": "session", "value": "...", "url": "..."}', null=True, verbose_name='Custom Cookies'),
        ),
    ]
