# Generated by Django 5.1.3 on 2025-04-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0017_alter_crawllink_blacklist_patterns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawllink',
            name='custom_cookies',
            field=models.JSONField(blank=True, default=list, help_text='Pre-set cookies, each a dict like {"name": "session", "value": "...", "url": "..."}', null=True, verbose_name='Custom Cookies'),
        ),
        migrations.AlterField(
            model_name='crawllink',
            name='url',
            field=models.URLField(verbose_name='Website-URL'),
        ),
    ]
