# Generated by Django 5.1.3 on 2025-04-07 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0019_alter_chatbot_chatbot_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebdavResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='Quell URL')),
                ('auth_user_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Benutzername')),
                ('auth_user_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Passwort')),
                ('deep', models.BooleanField(default=False, verbose_name='Rekursiv crawlen')),
                ('supported_extensions', models.CharField(blank=True, default='pdf,jpeg,jpg,JPG,png,PNG', max_length=255, null=True, verbose_name='Unterstützte Dateierweiterungen')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('last_crawl_start', models.DateTimeField(blank=True, null=True, verbose_name='Letzter Crawl-Start')),
                ('last_crawl_end', models.DateTimeField(blank=True, null=True, verbose_name='Letzter Crawl-Ende')),
                ('number_of_resources_processed', models.IntegerField(default=0, verbose_name='Anzahl verarbeiteter Ressourcen')),
                ('crawling_status', models.CharField(choices=[('pending', 'PENDING'), ('crawling', 'CRAWLING'), ('error', 'ERROR')], default='pending', max_length=20, verbose_name='Crawling-Status')),
                ('crawl_interval', models.IntegerField(default=0, help_text='Intervall für automatische Crawls in Tagen. 0 = keine automatischen Crawls.', verbose_name='Crawl-Intervall (Tage)')),
                ('deletion_timeout', models.IntegerField(default=0, help_text='Zeitraum in Tagen, nach dem Ressourcen gelöscht werden sollen. 0 = keine automatische Löschung.', verbose_name='Löschzeitraum (Tage)')),
                ('knowledgebase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.knowledgebase', verbose_name='Knowledgebase')),
            ],
            options={
                'verbose_name': 'WebDAV-Ressource',
                'verbose_name_plural': 'WebDAV-Ressourcen',
            },
        ),
    ]
