# Generated by Django 5.1.3 on 2025-04-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdav', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdavresource',
            name='starting_directory',
            field=models.CharField(default='/', help_text="Startverzeichnis relativ zum Start. Bspw. 'Beispiel/Ordner/'. Keine führenden '/'!", max_length=255),
        ),
    ]
