# Generated by Django 5.1.3 on 2025-04-08 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_create_user_profiles'),
        ('webdav', '0002_webdavresource_starting_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdavresource',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
        ),
    ]
