# Generated by Django 5.1.3 on 2025-04-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdav', '0003_webdavresource_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webdavresource',
            name='url',
            field=models.URLField(verbose_name='Quell URL'),
        ),
    ]
