<script setup>
import { onMounted, provide } from "vue"
import ChatWindow from "@/components/ChatWindow/ChatWindow.vue"
import { createI18Context } from "@padcom/vue-i18n"
import * as messages from "@/locales"
import { useConfig } from "@/composables/useConfig.ts"
import api from "@/services/api"

const loadSelectedLanguage = () => {
  return sessionStorage.getItem("selectedLanguage")
}

const locale = loadSelectedLanguage() ?? navigator.language.slice(0, 2)

createI18Context({ locale, messages, fallbackLocale: "en" })

const props = defineProps({
  isFullscreen: {
    type: Boolean
  },
  chatbotId: {
    type: String
  },
  apiUrl: {
    type: String
  },
  show: {
    type: Boolean,
    default: false
  },
  elementId: {
    type: String
  }
})

api.defaults.baseURL = props.apiUrl.replace(/\/$/, "")
const { config } = useConfig(props.chatbotId)

function disableBodyScroll() {
  document.body.style.overflowY = "hidden"
}

onMounted(() => {
  if (props.isFullscreen) {
    disableBodyScroll()
  }
})

const isInline = !!props.elementId

provide("isInline", isInline)
provide("isFullscreen", props.isFullscreen)
provide("chatbotId", props.chatbotId)
</script>

<template>
  <Transition name="scale-up-br">
    <div
      v-if="show && !!config"
      id="hw-chatbot"
      class="hw-chatbot"
      :class="[
        `hw-chatbot--variant-${config.variant}`,
        { 'hw-chatbot--fullscreen': isFullscreen, 'hw-chatbot--inline': isInline }
      ]"
    >
      <ChatWindow :chatbotId="props.chatbotId" :chatbotConfig="config" />
    </div>
  </Transition>
</template>

<style lang="scss">
@use "./styles/reset.scss";

.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border-width: 0;
}

/* ##### Layout ##### */

.hw-chatbot {
  max-height: 100%;
  width: 100%;
  height: 100dvh;
  top: unset;
  left: unset;
  right: 0;
  bottom: 0;
  position: fixed;
  z-index: 9999;
  overflow: hidden;

  @media screen and (min-width: 480px) {
    max-height: 700px;
    width: 400px;
    right: 2rem;
    box-shadow: rgba(129, 129, 129, 0.35) 0 0 8px;
    line-height: 1.3em;
    border-radius: 1.125rem 1.125rem 0 0;
  }

  &--variant-default,
  &--variant-glass {
    @media screen and (min-width: 480px) {
      width: 360px;
      bottom: 1rem;
      right: 1rem;
      height: calc(100dvh - 2rem);
      border-radius: 24px;
    }
  }

  &--fullscreen {
    height: 100dvh;
    width: 100%;
    position: fixed;
    -webkit-backface-visibility: hidden;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    border-radius: 0;
    overflow: unset;

    .chat-window-wrapper {
      height: 100dvh;
      width: 100%;
    }
  }

  &--inline {
    border-radius: 0;
    position: static;
    height: 100%;
    max-height: calc(100dvh - 100px);
    width: 100%;
    max-width: none;
  }
}

.chat-window-wrapper {
  position: relative;
  height: 100%;
}

.chat-window {
  width: 100%;
  height: 100%;
  max-height: 100vh;
  overflow: hidden;
}

.hw-chatbot--fullscreen .chat-window {
  width: 100%;
  max-width: none;
  border-radius: 0;
}

.chat-window__inner {
  height: 100%;
}

.hw-chatbot .chatbot-header {
  position: relative;
  z-index: 910;
}

.hw-chatbot--fullscreen .chat-window__footer,
.hw-chatbot--fullscreen .chat-content__inner {
  max-width: 1152px;
  margin: auto;
}

.code-copy-btn {
  position: absolute;
  top: 6px;
  right: 6px;
  transition: opacity 0.24s ease-out;
}

.code-copy-btn:hover {
  opacity: 0.6;
}

@media screen and (min-width: 480px) {
  .hw-chatbot--fullscreen .chat-window {
    max-height: 100%;
    right: 0;
  }
}

@media screen and (min-width: 1024px) {
  .hw-chatbot.hw-chatbot--fullscreen .chat-window__footer,
  .hw-chatbot.hw-chatbot--fullscreen .chat-content__inner {
    max-width: calc(100vw - (2 * 192px) - 52px); /* 192 -> Förderlogo */
    margin: auto;
  }

  .hw-chatbot.hw-chatbot--fullscreen .chat-window__footer {
    margin-bottom: 8px;
  }
}

@media screen and (min-width: 1600px) {
  .hw-chatbot.hw-chatbot--fullscreen .chat-window__footer,
  .hw-chatbot.hw-chatbot--fullscreen .chat-content__inner {
    max-width: 1152px;
  }
}

.scale-up-br {
  -webkit-animation: scale-up-br 0.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: scale-up-br 0.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}

.scale-up-br-enter-active {
  animation: scale-up-br 0.2s;
}

.scale-up-br-leave-active {
  animation: scale-up-br 0.2s reverse;
}

/* ----------------------------------------------
 * Generated by Animista on 2024-11-26 8:31:42
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-br
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-br {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
    -webkit-transform-origin: 100% 100%;
    transform-origin: 100% 100%;
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-transform-origin: 100% 100%;
    transform-origin: 100% 100%;
  }
}

@keyframes scale-up-br {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
    -webkit-transform-origin: 100% 100%;
    transform-origin: 100% 100%;
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-transform-origin: 100% 100%;
    transform-origin: 100% 100%;
  }
}
</style>
