# Generated by Django 5.1.3 on 2025-02-27 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0019_alter_chatbot_chatbot_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphQlResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('query', models.TextField()),
                ('last_crawled', models.CharField(blank=True, help_text='ID of the last crawl task', max_length=255, null=True)),
                ('field_mappings', models.JSONField(blank=True, default=dict, help_text="JSON configuration for field mappings. Use this to customize how fields are converted to markdown. Example: {'title_field': 'name', 'image_fields': ['thumbnail', 'image'], 'link_fields': {'url': 'https://example.com/{path}'}}")),
                ('unwrap_node_field', models.CharField(blank=True, help_text="Field name to unwrap from edges/node structure. For GraphQL responses with structure like edges:[{node:{...}}, {node:{...}}], set this to 'node' to extract the contents of each node.", max_length=50, null=True)),
                ('knowledgebase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.knowledgebase', verbose_name='Knowledgebase')),
            ],
            options={
                'verbose_name': 'GraphQL Resource',
                'verbose_name_plural': 'GraphQL Resources',
            },
        ),
    ]
