# Generated by Django 5.1.3 on 2025-02-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphqlresource',
            name='pagination_batch_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graphqlresource',
            name='pagination_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graphqlresource',
            name='pagination_total_count_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
