# Generated by Django 5.1.3 on 2025-02-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql', '0002_graphqlresource_pagination_batch_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphqlresource',
            name='item_identification_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='graphqlresource',
            name='pagination_max_pages',
            field=models.IntegerField(default=0),
        ),
    ]
