# Generated by Django 5.1.3 on 2025-03-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql', '0003_graphqlresource_item_identification_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphqlresource',
            name='item_identification_field',
            field=models.CharField(blank=True, help_text='Result Representation of some kind of item id, to update entries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='graphqlresource',
            name='pagination_batch_size',
            field=models.IntegerField(default=0, help_text='Number of items to fetch per request. Set to 0 to fetch all items.'),
        ),
        migrations.AlterField(
            model_name='graphqlresource',
            name='pagination_max_pages',
            field=models.IntegerField(default=0, help_text='Limit the amount of pages retrieved by the pagination.'),
        ),
        migrations.AlterField(
            model_name='graphqlresource',
            name='pagination_start',
            field=models.IntegerField(default=0, help_text='Start of the pagination. Default is to start with the first item found.'),
        ),
        migrations.AlterField(
            model_name='graphqlresource',
            name='pagination_total_count_field',
            field=models.CharField(blank=True, help_text='Field in the Result that represents the total number of items found with the query.', max_length=255, null=True),
        ),
    ]
