# Generated by Django 5.1.3 on 2025-03-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql', '0005_graphqlresource_result_metadata_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphqlresource',
            name='extract_document_resources',
            field=models.BooleanField(default=False, help_text='Whether or not to extract documents from this resource.'),
        ),
    ]
