# Generated by Django 5.1.3 on 2025-03-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql', '0006_graphqlresource_extract_document_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphqlresource',
            name='source_identification_field',
            field=models.CharField(blank=True, help_text='key of the item taht represents some kind of source url. for example the link to an online catalogue', max_length=255, null=True),
        ),
    ]
