# Generated by Django 5.1.3 on 2025-03-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql', '0007_graphqlresource_source_identification_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphqlresource',
            name='source_url_template',
            field=models.CharField(blank=True, help_text='Template for source URLs. Use placeholders like {field_name} to insert values from the response. Example: https://app.example.com/{language}/items/{item_id}', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='graphqlresource',
            name='source_identification_field',
            field=models.CharField(blank=True, help_text='Key of the item that represents some kind of source url. For example the link to an online catalogue. This is used if source_url_template is not defined.', max_length=255, null=True),
        ),
    ]
