# Generated by Django 5.1.3 on 2025-03-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql', '0008_graphqlresource_source_url_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphqlresource',
            name='source_identification_field',
        ),
    ]
