# Generated by Django 5.1.3 on 2025-04-08 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_create_user_profiles'),
        ('graphql', '0009_remove_graphqlresource_source_identification_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphqlresource',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
        ),
    ]
